CREATE TABLE DimGenre
(
  ID_GENRE INT IDENTITY(1,1) PRIMARY KEY
, GENRE VARCHAR(100) NOT NULL
);

INSERT INTO [DW_OLYMPICS].[dbo].[DimGenre] (GENRE) VALUES ('Male');
INSERT INTO [DW_OLYMPICS].[dbo].[DimGenre] (GENRE) VALUES ('Female');

CREATE TABLE DimDicipline
(
  ID_DICIPLINE INT IDENTITY(1,1) PRIMARY KEY
, DICIPLINE VARCHAR(100) NOT NULL
);

CREATE TABLE FaitDG
(
  ID_DICIPLINE INT NOT NULL
  , ID_GENRE INT NOT NULL
  , CONSTRAINT PK_FaitDG PRIMARY KEY NONCLUSTERED (ID_DICIPLINE, ID_GENRE)
  , CONSTRAINT FK_DimDicipline_FaitDG FOREIGN KEY (ID_DICIPLINE)
        REFERENCES DimDicipline (ID_DICIPLINE)
        ON DELETE CASCADE
        ON UPDATE CASCADE
  , CONSTRAINT FK_DimGenre_FaitDG FOREIGN KEY (ID_GENRE)
        REFERENCES DimGenre (ID_GENRE)
        ON DELETE CASCADE
        ON UPDATE CASCADE
  , NB_ATHLETES INT
);